name: Build and Deploy Docs

on:
  push:
    branches: [devel]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Build Doxygen C++ API Docs
        run: doxygen docs/config.cpp.cfg
      
      - name: Build Doxygen Python API Docs
        run: doxygen docs/config.py.cfg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
