name: Build and Deploy Docs

on:
  push:
    branches: [devel]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt install -y doxygen
          pip install sphinx myst-parser
        
      - name: Build Doxygen C++ API Docs
        run: doxygen docs/config.cpp.cfg
      
      - name: Build Doxygen Python API Docs
        run: doxygen docs/config.py.cfg

      - name: Build Python docs (Sphinx)
        run: sphinx-build -b html docs/python/ docs/api/python/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
