name: Build and Deploy Docs

on:
  push:
    branches: [devel]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install doc tools
        run: |
          sudo apt install -y doxygen
          pip install sphinx myst-parser sphinx_rtd_theme 
          
      - name: Build Doxygen C++ API Docs
        run: doxygen docs/api/cpp/config.cpp.cfg

      - name: Build Python docs (Sphinx)
        run: |
          sphinx-apidoc -o docs/api/python ./specd
          sphinx-build -b html docs/ docs/_build/
      
      - name: Build master docs (Sphinx)
        run: 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
